### PR TITLE
Extend menu context with issues.

### PR DESCRIPTION
**Pull request by mantykora-net**
On launching context menu customizations, selected issues and their respective custom values are available in View.context.issues

### CODE REVIEW

**Comment by onozaty** [comment]
Thanks for the merge request.

I would like to consider what to do with the Issue information, including other Insertion positions.

**Comment by mantykora-net** [comment]
The thought behind this was that the menu position is different since it has no other sources to work from in show/form you can pull the data form the form fields or DOM but there you just have the nested lists for the menu.

**Comment by onozaty** [comment]
I am considering incorporating this suggestion itself.
However, not being able to refer to it in other similar screens may be confusing to users.
We are thinking of making it available in the "Bottom of issue detail" as well.
Also, I am thinking of adding other information as well, since it would not feel right to have only custom fields.

The test and README have not been changed, so we will modify them as well.

**Comment by onozaty** [comment]
Hi @mantykora-net 
This merge request does not appear to return any information about the issue, is it working as intended?

**Comment by onozaty** [comment]
> Hi @mantykora-net This merge request does not appear to return any information about the issue, is it working as intended?

I fixed it here and tried to make it work.

However, I think the current contents of ViewCustomize.context.issues is in a very confusing format.

```javascript
ViewCustomize.context.issues = [{"id":2,"tracker_id":1,"project_id":1,"subject":"aaaaa","description":"","due_date":null,"category_id":null,"status_id":1,"assigned_to_id":null,"priority_id":2,"fixed_version_id":null,"author_id":1,"lock_version":1,"created_on":"2023-02-19T14:13:40.347Z","updated_on":"2023-02-19T14:13:40.347Z","start_date":"2023-02-19","done_ratio":0,"estimated_hours":null,"parent_id":null,"root_id":2,"lft":1,"rgt":2,"is_private":false,"closed_on":null,"custom_values":[{"id":1,"customized_type":"Issue","customized_id":2,"custom_field_id":1,"value":"xxxx"}]}];
```

Therefore, we would like to refrain from incorporating it into the plugin itself at this time.

I am sorry for your proposal.

**Pull request merged**
