### PR TITLE
Fix problem with view_customize/view_hook not loading caused by Zeitwerk support

### PR DESCRIPTION
**Pull request by ishikawa999**
I think the problem with #84 will be solved by this change.
Changed the way to write the path passed to require.

### CODE REVIEW

**Comment by onozaty** [comment]
Thank you for your support.

I will try it on my end and merge it if there is no problem.
I hope you can give me some more time.

**Comment by onozaty** [comment]
I tried it.

This problem was solved, but then I got the following error.

```
App 12832 output: Error: The application encountered the following error: uninitialized constant ViewCustomize::ViewHook (NameError)
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `instance_exec'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `run'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:60:in `run_initializers'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/application.rb:391:in `initialize!'
App 12832 output:     /var/lib/redmine/config/environment.rb:16:in `<top (required)>'
App 12832 output:     config.ru:3:in `require'
App 12832 output:     config.ru:3:in `block in <main>'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 12832 output:     /var/lib/redmine/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 12832 output:     config.ru:1:in `new'
App 12832 output:     config.ru:1:in `<main>'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 12832 output:     /usr/local/rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-11-19 12:35:56.2355 12806/Tc age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/lib/redmine: The application encountered the following error: uninitialized constant ViewCustomize::ViewHook (NameError)
  Error ID: 97bac37e
  Error details saved to: /tmp/passenger-error-rO8XjX.html
```

The environment we tried is as follows.
```
Environment:
  Redmine version                4.2.3.devel.21289
  Ruby version                   3.0.0-p0 (2020-12-25) [x86_64-linux]
  Rails version                  6.1.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem    
```

I will check some more.

**Comment by onozaty** [comment]
There was a mismatch between the directory name and the module name, which caused the error.

* lib/view_customize/view_hook.rb
* RedmineViewCustomize::ViewHook

I will fix and release this issue as well.

Thanks.

**Comment by onozaty** [comment]
It has been released as v3.0.0.
Thank you very much.

**Comment by ishikawa999** [comment]
@onozaty 
I was not able to sufficiently verify the operation.
Thank you for the additional support.

**Pull request merged**
